---
title: "Statistical models and methods"
execute:
  echo: false
  warning: false
  message: false
format:
  docx:
    fig-height: 6
    fig-width: 8
bibliography: refs.bib
csl: vancouver-brackets.csl
---

# Statistical models

We applied GLMs (generalized linear models) to explain the level of microplastics and PFAS as a function of sample characteristics (category, source, bottle material, advanced treatment). We fit zero-inflated models to account for the over-abundance of zeroes, in this case because many samples had no-detection of microplastics or PFAS.

For the microplastics analysis, we fit four models: total microplastics, total microplastics in bottled samples only, PE-only microplastics in bottled samples only, and PET-only microplastics in bottled samples only. For each response we fit a zero-inflated negative binomial model. The negative binomial model was applied to accommodate the observed overdispersion compared to a Poisson model. We compared fitting Poisson models, negative binomial models, zero-inflated Poisson models, and zero-inflated negative binomials. The final model specification was chosen by (1) comparing the number of zeros predicted by the models to the true number of zeros, (2) evaluating overdispersion through the ratio of the deviance to the degrees of freedom, and (3) likelihood ratio tests for nested models. The final models were also evaluated using standard regression diagnostics to check for divergence from the expected residual distribution, overdispersion, outliers, and heterogeneity. The final models were deemed to have sufficiently good model fit for the results to be reliable.

The microplastics model for total microplastics in bottled samples has very large standard errors for the zero-inflated component. This is likely due to a combination of factors. First, the small sample size may be a factor, as only 6 bottled samples had no microplastics detected. Most likely, the main driving factor is the collinearity between the source type and advanced filtration. All the samples with advanced filtration applied come from non-spring sources. Most likely this collinearity is causing the large standard errors. Because of the large standard errors, the probabilty of detection from this model is not informative, and we instead report p-values from exact two-sample Fisher-Pitman permutation tests. This exact test is optimized for small samples, and performs well even when one of the proportions is zero. A standard z-test for proportions does not necessarily perform as well in small samples or when one of the proportions is zero.

Due to the issues with high collinearity, we cannot disentangle the association with source from the association with advanced filtration.

For the microplastics models, for the conditional (mean) part of the model, we report 95% confidence intervals for the incidence rate ratio. For the zero-inflation part of the model, we report 95% confidence intervals for the odds ratio and relative risk. Both these values can be interpreted as a multiplicative effect.

For the PFAS analyses, we fit one model: PFAS concentration regressed on category (bottled v. municipal). We initially fit a PFAS model with concentration regressed on category (bottled v. municipal, if relevant), source type (spring v. non-spring), and advanced filtration (yes or no). However, this model is degenerate because the covariate matrix is singular. This model suffers from the same problems as the microplastics model, namely that souce type and advanced filtration are highly collinear. So again, we report exact two-sample Fisher-Pitman permutation tests for source type and advanced filtration.

The PFAS concentration model is a zero-inflated gamma models. Unlike for microplastics, the data is continuous, so the gamma distribution accounts for the continuous skewed response. We compared fitting zero-inflated gamma with log link, zero-inflated gaussian, zero-inflated log-normal, zero-inflated  Poisson, and tweedie models. The number of zeros was similar between all models, so it was not a useful model diagnostic. We could not apply likelihood ratio tests as we could for the microplastics models because the models were not nested. Instead, the final model was chosen using standard regression diagnostics to check for divergence from the expected residual distribution, overdispersion, outliers, and heterogeneity. The zero-inflated gamma was chosen because it was deemed to have the best fit based on regression diagnostics.

For the PFAS model, for the conditional (mean) part of the model, we report 95% confidence intervals for the ratio of means. For the zero-inflation part of the model, we report 95% confidence intervals for the odds ratio and relative risk. Both these values can be interpreted as a multiplicative effect.

All analyses were conducted in `R`/`RStudio` [@RTeam2026; @RstudioTeam2026].  We used the following packages: `tidyverse` [@Wickham2019] for data processing, `glmmTMB` [@glmmTMB2017; @glmmTMB2025] to fit the models, `DHARMa` [@dharma2026] to evaluate the models, and `coin`[@coin2006; @coin2008] for the permutation test.

```{r}
#toBibtex(citation("glmmTMB"))
#toBibtex(citation("DHARMa"))
#toBibtex(citation("coin"))
```

There were a small number of bottled water samples where the categories were unclear based on the label or other publicly available information. For one brand it was unclear if the source was spring or non-spring water, and for another brand it was unclear if advanced treatment was applied. We conducted the analysis assuming the first brand was non-spring water, and that the second brand did not have advanced treatment applied. We conducted a sensitivity analysis by re-analyzing all the data with the opposite categorization for these two brands, and the conclusions did not change. Individual numbers and p-values changed, but only by small amounts.

# References
